# Generated by Django 5.1.6 on 2025-02-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("""
                create table if not exists blog_post (
                    id serial primary key,
                    title varchar,
                    content text,
                    created_at date default now()
                );
                """)
            ], 
            reverse_sql=[
                ("""
                drop table if exists blog_post;
                """)
            ])
    ]
